Add list subcommand to dialog
Yuuto-Project/kyuuto pull request #24
Opened 2020-07-13 19:22 UTC by duncte123

2020-07-13 19:26 UTC, zsotroav requested changes
Other than that, it's good.

2020-07-13 19:26 UTC, zsotroav commented on src/main/kotlin/io/github/yuutoproject/yuutobot/commands/Dialog.kt
> +            event.channel.sendMessage("""Here are the lists of characters and backgrounds that you can use
```suggestion
            event.channel.sendMessage("""Here are the lists of characters and backgrounds that you can use:
```
Minor issue.

2020-07-13 19:29 UTC, zsotroav submitted a review, later dismissed

2020-07-13 19:47 UTC, zsotroav approved these changes

2020-07-14 01:57 UTC, Leguu approved these changes

2020-07-14 04:55 UTC, merged